#!/usr/bin/env bash
# script that tells the story of the /etc/passwd file
while IFS=":" read -r username _ userid groupid _ homedir shell; do 
echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $username"
done < /etc/passwd
