#!/usr/bin/env bash
# script that groups visitors by IP and HTTP status code, and displays this data
awk '{print $1,$7,$9}' /path/to/apache.log | 
awk '{if($3 ~ /^[0-9]+$/) print $1,$2,$3}'
sort -k2,2 -k3,3n |
uniq -c |
sort -nr |
awk '{print $1,$3,$2}' 
