#!/usr/bin/env bash
# script that displays Best School 10 times
# Initialize a counter
count=0
# use a while loop to display "Best School" 10 times
while [$count -lt 10 ]; do 
echo "Best School"
# Increment the counter
count=$((count + 1))
done 
