#!/usr/bin/env bash
# script that displays  The content of the current directory, In a list format, Where only the part of the name after the first dash is displayed
for file in *; do
if [[ $file != .* ]]; then
display_name=$(echo "$file" | cut -d '-' -f 2-)
echo "display_name"
fi
done
