#!/usr/bin/env bash
# i love you
PID_FILE="/var/run/myscript.pid"
cleanup() {
	rm -f "$PID_FILE"
	exit 0
}
trap 'cleanup' SIGTERM SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"' SIGTERM
echo $$ > "$PID_FILE"
while true; do 
	echo "To infinity and beyond"
	sleep 1
done
