#!/usr/bin/env bash
# i love you
PID_FILE="/var/run/myscript.pid"
cleanup() {
	echo "I hate the kill command"
	rm -f "$PID_FILE"
	exit 1
}
interrupt() {
echo "Y U no love me?!"
}
quit() {
	echo "Y U no love me?!"
	rm -f "$PID_FILE"
	exit 0
}
trap cleanup SIGTERM
trap interrupt SIGINT
trap quit SIGQUIT
echo $$ > "$PID_FILE"
while true; do 
	echo "To infinity and beyond"
	sleep 1
done
