#!/usr/bin/env bash
#manage
MANAGE_SCRIPT="/path/to/manage_my_process"
PID_FILE="/var/run/my_process.pid"
start() {
	if [ -f "$PID_FILE" ]; then
	echo "manage_my_process started"
	fi
}
stop () {
	if [ -f "$PID_FILE" ]; then
	kill "$(cat "$PID_FILE")"
	rm "$PID_FILE"
	echo "manage_my_process started"
else
	echo "manage_my_process is not running."
       	fi
}
restart() {
	stop
	start
	echo "manage_my_process restarted"
}
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
exit 0
