#!/usr/bin/env bash
# script that stops 4-to_infinity_and_beyond process
pid=$(pgrep -f "4-to_infinity_and_beyond")
if [ -n "$pid" ]; then
kill "$pid"
echo "process with PID "$pid has been terminated."
else
echo "Process 4-to_infinity_and_beyond not found"
fi
