#!/usr/bin/env bash
# script that stops 4-to_infinity_and_beyond process
pid=$(pgrep -f "4-to_infinity_and_beyond")
if [ -n "$pid" ]; then 
kill -SIGNT "$pid"
echo "sent SIGNT to process with PID $pid."
else
echo "process 4-to_infinity_and_beyond not found."
fi
